In [ ]:
  # importing the packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing

In [ ]:
import warnings
warnings.filterwarnings('always')
warnings.filterwarnings('ignore')# data visualisation and manipulationimport numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns
import missingno as msno#configure
# sets matplotlib to inline and displays graphs below the corressponding cell.
%matplotlib inline
style.use('fivethirtyeight')
sns.set(style='whitegrid',color_codes=True)#import the necessary modelling algos.
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

#model selection
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score,precision_score
from sklearn.model_selection import GridSearchCV#preprocess.
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [ ]:
#importing the dataset
url="drive/MyDrive/NS/Lab/MachineLearningCSV/CSVs/dataset.csv"
df = pd.read_csv(url)

In [ ]:
print(df.shape)
df1=df.drop(['Unnamed: 0'], axis =1)
N=1000000
df2=df1.groupby('Label', group_keys=False).apply(lambda x: x.sample(int(np.rint(N*len(x)/len(df1))))).sample(frac=1).reset_index(drop=True)

(2830743, 80)


In [ ]:
df1["Label"].value_counts()

BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: Label, dtype: int64

In [ ]:
df2

Destination_Port  Flow_Duration  ...  Idle_Min     Label
0                   7921             48  ...         0  PortScan
1                     80       84733276  ...  84600000  DoS Hulk
2                     53         605070  ...         0    BENIGN
3                    443       10137210  ...   9999540    BENIGN
4                    443          38797  ...         0    BENIGN
...                  ...            ...  ...       ...       ...
999995              1862            105  ...         0    BENIGN
999996                80       70979131  ...   7425847      DDoS
999997                53            205  ...         0    BENIGN
999998                80        5532573  ...         0    BENIGN
999999               445           1311  ...         0  PortScan

[1000000 rows x 79 columns]

In [ ]:
df2.shape

(1000000, 79)

In [ ]:
df2.groupby(['Label']).transform('count').nunique()

Destination_Port               15
Flow_Duration                  15
Total_Fwd_Packets              15
Total_Backward_Packets         15
Total_Length_of_Fwd_Packets    15
                               ..
Active_Min                     15
Idle_Mean                      15
Idle_Std                       15
Idle_Max                       15
Idle_Min                       15
Length: 78, dtype: int64

In [ ]:
# Replacing infinite with nan
df2.replace([np.inf, -np.inf], np.nan, inplace=True)

# Dropping all the rows with nan values
df2.dropna(inplace=True)

# Printing df
df2

Destination_Port  Flow_Duration  ...   Idle_Min             Label
0                     80      109670936  ...  110000000  DoS Slowhttptest
1                     53            297  ...          0            BENIGN
2                     53            244  ...          0            BENIGN
3                    443          94900  ...          0            BENIGN
4                     80       73239802  ...    6502424              DDoS
...                  ...            ...  ...        ...               ...
999995              3312             28  ...          0            BENIGN
999996                53         284137  ...          0            BENIGN
999997              3784             37  ...          0          PortScan
999998              5098             50  ...          0            BENIGN
999999                53          50752  ...          0            BENIGN

[999028 rows x 79 columns]

In [ ]:
df2=df2.drop(['Destination_Port'],axis=1)

In [ ]:
df2.shape

(998993, 78)

In [ ]:
df2["Label"].value_counts()

BENIGN                        802346
DoS Hulk                       81296
PortScan                       56093
DDoS                           45226
DoS GoldenEye                   3636
FTP-Patator                     2803
SSH-Patator                     2083
DoS slowloris                   2048
DoS Slowhttptest                1943
Bot                              693
Web Attack � Brute Force         532
Web Attack � XSS                 230
Infiltration                      13
Web Attack � Sql Injection         7
Heartbleed                         4
Name: Label, dtype: int64

In [ ]:
df2.isnull().values.all()

False

In [ ]:
df2

Flow_Duration  Total_Fwd_Packets  ...  Idle_Min        Label
0                 156                  2  ...         0       BENIGN
1            85365947                 20  ...  25500000       BENIGN
2                 150                  2  ...         0       BENIGN
3                   3                  2  ...         0       BENIGN
4             8584262                  9  ...         0  FTP-Patator
...               ...                ...  ...       ...          ...
999995        5566006                  3  ...         0       BENIGN
999996            464                  1  ...         0       BENIGN
999997         248164                  2  ...         0       BENIGN
999998            208                  2  ...         0       BENIGN
999999            222                  2  ...         0       BENIGN

[998993 rows x 78 columns]

In [ ]:
X = df2.drop(['Label'], axis=1)
X.head()

Flow_Duration  Total_Fwd_Packets  ...   Idle_Max   Idle_Min
0      109670936                  4  ...  110000000  110000000
1            297                  2  ...          0          0
2            244                  2  ...          0          0
3          94900                  1  ...          0          0
4       73239802                  6  ...   64900000    6502424

[5 rows x 77 columns]

In [ ]:
for col in X:
  print("col name: ",col," no of unique classes: ",X[col].nunique())

col name:  Flow_Duration  no of unique classes:  425050
col name:  Total_Fwd_Packets  no of unique classes:  913
col name:  Total_Backward_Packets  no of unique classes:  1127
col name:  Total_Length_of_Fwd_Packets  no of unique classes:  11614
col name:  Total_Length_of_Bwd_Packets  no of unique classes:  34178
col name:  Fwd_Packet_Length_Max  no of unique classes:  4242
col name:  Fwd_Packet_Length_Min  no of unique classes:  288
col name:  Fwd_Packet_Length_Mean  no of unique classes:  51309
col name:  Fwd_Packet_Length_Std  no of unique classes:  106121
col name:  Bwd_Packet_Length_Max  no of unique classes:  4304
col name:  Bwd_Packet_Length_Min  no of unique classes:  485
col name:  Bwd_Packet_Length_Mean  no of unique classes:  69919
col name:  Bwd_Packet_Length_Std  no of unique classes:  102279
col name:  Flow_Bytess  no of unique classes:  597343
col name:  Flow_Packetss  no of unique classes:  484146
col name:  Flow_IAT_Mean  no of unique classes:  458082
col name:  Flow_IA

In [ ]:
X.shape

(998993, 77)

In [ ]:
y = df2['Label']
y.head()
print("label no of unique classes: ", y.nunique())

label no of unique classes:  15


In [ ]:
y.shape

(998993,)

In [ ]:
y

0           BENIGN
1           BENIGN
2           BENIGN
3           BENIGN
4           BENIGN
            ...   
999995      BENIGN
999996    PortScan
999997      BENIGN
999998      BENIGN
999999    DoS Hulk
Name: Label, Length: 998943, dtype: object

In [ ]:
# Integer Encoding
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print(y)

[ 5  0  0 ... 10  0  0]


In [ ]:
y1= pd.DataFrame(y)

In [ ]:
y1.shape

(999028, 1)

In [ ]:
y1

0
0       10
1        4
2        0
3        0
4        0
...     ..
998948   0
998949   2
998950   0
998951   0
998952  10

[998953 rows x 1 columns]

In [ ]:
# sns.countplot(data=y1)
# y1.value_counts()

In [ ]:
# one hot encoding for y
# Integer Encoding
label_encoder = LabelEncoder()
y_label = label_encoder.fit_transform(y)
print(y_label)


#reshaping for OneHotEncoder
y_label_reshape = y_label.reshape(len(y_label), 1)

# One-Hot Encoding
onehot_encoder = OneHotEncoder(sparse=False)
y_one = onehot_encoder.fit_transform(y_label_reshape)
print(y_one)

[0 0 0 ... 0 0 0]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Normalizing numerical columns
# define standard scaler
scaler = preprocessing.MinMaxScaler()
# transform data
for col in X:
  print("normalized feature using Minmax scaler: ",col)
  X[col]=scaler.fit_transform(pd.to_numeric(X[col],errors='coerce').values.reshape(-1,1))

normalized feature using Minmax scaler:  Flow_Duration
normalized feature using Minmax scaler:  Total_Fwd_Packets
normalized feature using Minmax scaler:  Total_Backward_Packets
normalized feature using Minmax scaler:  Total_Length_of_Fwd_Packets
normalized feature using Minmax scaler:  Total_Length_of_Bwd_Packets
normalized feature using Minmax scaler:  Fwd_Packet_Length_Max
normalized feature using Minmax scaler:  Fwd_Packet_Length_Min
normalized feature using Minmax scaler:  Fwd_Packet_Length_Mean
normalized feature using Minmax scaler:  Fwd_Packet_Length_Std
normalized feature using Minmax scaler:  Bwd_Packet_Length_Max
normalized feature using Minmax scaler:  Bwd_Packet_Length_Min
normalized feature using Minmax scaler:  Bwd_Packet_Length_Mean
normalized feature using Minmax scaler:  Bwd_Packet_Length_Std
normalized feature using Minmax scaler:  Flow_Bytess
normalized feature using Minmax scaler:  Flow_Packetss
normalized feature using Minmax scaler:  Flow_IAT_Mean
normalized feat

In [ ]:
#pd.DataFrame(y_one, columns=['predictions']).to_csv('y_one.csv')

In [ ]:
X.shape

(999028, 77)

In [ ]:
#saving dataframe to csv in the drive
X.to_csv(r'drive/MyDrive/NS/Lab/MachineLearningCSV/CSVs/X_prepro.csv')

In [ ]:
X50 = X[['Average_Packet_Size','Packet_Length_Std', 'Packet_Length_Mean', 'Packet_Length_Variance', 'Subflow_Bwd_Bytes','Total_Length_of_Bwd_Packets','Avg_Bwd_Segment_Size','Bwd_Packet_Length_Mean','Init_Win_bytes_forward','Subflow_Fwd_Bytes','Total_Length_of_Fwd_Packets','Bwd_Packet_Length_Max','Max_Packet_Length','Init_Win_bytes_backward','Fwd_Packet_Length_Max','Flow_IAT_Max','Flow_Bytess','Flow_Duration','Fwd_IAT_Max','Fwd_Header_Length','Fwd_Header_Length.1','Avg_Fwd_Segment_Size','Fwd_Packet_Length_Mean','Fwd_Packetss','Bwd_Packetss','Fwd_IAT_Total','Flow_Packetss','Bwd_Header_Length','Flow_IAT_Mean','Fwd_IAT_Mean','Bwd_Packet_Length_Std','Flow_IAT_Std','Fwd_Packet_Length_Std','Fwd_IAT_Std','Bwd_IAT_Max','Subflow_Bwd_Packets','Total_Backward_Packets','Bwd_IAT_Total','Subflow_Fwd_Packets','Total_Fwd_Packets','Bwd_IAT_Mean','Bwd_Packet_Length_Min','Idle_Max','min_seg_size_forward','Idle_Mean','Idle_Min','Bwd_IAT_Std','Fwd_IAT_Min','Active_Mean']]


In [ ]:
X40 = X[['Average_Packet_Size','Packet_Length_Std', 'Packet_Length_Mean', 'Packet_Length_Variance', 'Subflow_Bwd_Bytes','Total_Length_of_Bwd_Packets','Avg_Bwd_Segment_Size','Bwd_Packet_Length_Mean','Init_Win_bytes_forward','Subflow_Fwd_Bytes','Total_Length_of_Fwd_Packets','Bwd_Packet_Length_Max','Max_Packet_Length','Init_Win_bytes_backward','Fwd_Packet_Length_Max','Flow_IAT_Max','Flow_Bytess','Flow_Duration','Fwd_IAT_Max','Fwd_Header_Length','Fwd_Header_Length.1','Avg_Fwd_Segment_Size','Fwd_Packet_Length_Mean','Fwd_Packetss','Bwd_Packetss','Fwd_IAT_Total','Flow_Packetss','Bwd_Header_Length','Flow_IAT_Mean','Fwd_IAT_Mean','Bwd_Packet_Length_Std','Flow_IAT_Std','Fwd_Packet_Length_Std','Fwd_IAT_Std','Bwd_IAT_Max','Subflow_Bwd_Packets','Total_Backward_Packets','Bwd_IAT_Total','Subflow_Fwd_Packets']]

In [ ]:
X50

Average_Packet_Size  Packet_Length_Std  ...   Fwd_IAT_Min  Active_Mean
0                  0.013960           0.026140  ...  5.333333e-06     0.000052
1                  0.032302           0.014817  ...  1.333333e-07     0.000000
2                  0.031012           0.015165  ...  1.083333e-07     0.000000
3                  0.000000           0.000000  ...  9.999999e-08     0.000000
4                  0.316422           0.738485  ...  6.249999e-07     0.000008
...                     ...                ...  ...           ...          ...
999995             0.003732           0.002363  ...  1.083333e-07     0.000000
999996             0.032302           0.011470  ...  9.999999e-08     0.000000
999997             0.001357           0.000488  ...  9.999999e-08     0.000000
999998             0.003732           0.002363  ...  1.083333e-07     0.000000
999999             0.026602           0.003417  ...  9.999999e-08     0.000000

[999028 rows x 49 columns]

In [ ]:
X40

Average_Packet_Size  ...  Subflow_Fwd_Packets
0                  0.022731  ...             0.000005
1                  0.013613  ...             0.000005
2                  0.030758  ...             0.000005
3                  0.000771  ...             0.000000
4                  0.002312  ...             0.000005
...                     ...  ...                  ...
999995             0.003403  ...             0.000009
999996             0.011045  ...             0.000005
999997             0.007384  ...             0.000005
999998             0.156406  ...             0.000300
999999             0.204144  ...             0.000036

[999029 rows x 39 columns]

In [ ]:
#saving dataframe to csv in the drive
X40.to_csv(r'drive/MyDrive/NS/Lab/MachineLearningCSV/CSVs/X40_prepro.csv')

In [ ]:
#saving dataframe to csv in the drive
X50.to_csv(r'drive/MyDrive/NS/Lab/MachineLearningCSV/CSVs/X50_prepro.csv')

In [ ]:
print(y1.index.name)

None


In [ ]:
y1.head()

Label
0      0
1      0
2      0
3      0
4      7

In [ ]:
y1.rename(columns={0:'Label'}, inplace=True)

In [ ]:
y1.nunique()

Label    15
dtype: int64

In [ ]:
y1.shape

(998984, 1)

In [ ]:
y1.to_csv(r'drive/MyDrive/NS/Lab/MachineLearningCSV/CSVs/y_prepro.csv')

In [ ]:
# Train Test Split
x_train, x_test, y_train, y_test = train_test_split(X, y1, test_size=0.3, random_state=101)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((699295, 77), (699295, 1), (299698, 77), (299698, 1))

In [ ]:
X

Flow_Duration  Total_Fwd_Packets  ...  Idle_Max  Idle_Min
0                 156                  2  ...         0         0
1            85365947                 20  ...  58500000  25500000
2                 150                  2  ...         0         0
3                   3                  2  ...         0         0
4             8584262                  9  ...         0         0
...               ...                ...  ...       ...       ...
999995        5566006                  3  ...         0         0
999996            464                  1  ...         0         0
999997         248164                  2  ...         0         0
999998            208                  2  ...         0         0
999999            222                  2  ...         0         0

[998993 rows x 77 columns]

In [ ]:
x_train.head(5)

Flow_Duration  Total_Fwd_Packets  ...  Idle_Max  Idle_Min
269778   5.257048e-01           0.000027  ...  0.266667  0.066799
788774   4.333333e-07           0.000005  ...  0.000000  0.000000
277696   1.550000e-06           0.000005  ...  0.000000  0.000000
76662    9.502915e-01           0.000086  ...  0.083333  0.083001
913025   1.336459e-02           0.000009  ...  0.000000  0.000000

[5 rows x 77 columns]

#### running random forest and decision tree

In [ ]:
models=[RandomForestClassifier(), DecisionTreeClassifier()]
model_names=['RandomForestClassifier','DecisionTree']
acc=[]
d={}
for model in range(len(models)):
    clf=models[model]
    clf.fit(x_train,y_train)
    pred=clf.predict(x_test)
    acc.append(accuracy_score(pred,y_test))

d={'Modelling Algo':model_names,'Accuracy':acc}

In [ ]:
acc_frame=pd.DataFrame(d)
acc_frame

In [ ]:
param_grid = {
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}
CV_rfc = GridSearchCV(estimator=RandomForestClassifier(), param_grid=param_grid, scoring='accuracy', cv= 5)
CV_rfc.fit(x_train, y_train)

In [ ]:
print("Best score : ",CV_rfc.best_score_)
print("Best Parameters : ",CV_rfc.best_params_)
print("Precision Score : ", precision_score(CV_rfc.predict(x_test),y_test))

In [ ]:
df1 = pd.DataFrame.from_records(x_train)
tmp = pd.DataFrame({'Feature': df1.columns, 'Feature importance': clf_rf.feature_importances_})
tmp = tmp.sort_values(by='Feature importance',ascending=False)
plt.figure(figsize = (7,4))
plt.title('Features importance',fontsize=14)
s = sns.barplot(x='Feature',y='Feature importance',data=tmp)
s.set_xticklabels(s.get_xticklabels(),rotation=90)
plt.show()

#### running models
random forest

In [ ]:
# let us create and run different models on the dataset
# let us use randomforest
# import libraries
from sklearn.ensemble import RandomForestClassifier
ml=RandomForestClassifier(n_estimators=100)
import time
stime = time.time()
ml.fit(X_train,y_train)
print("--- %s seconds needed to train ---" % (time.time() - stime))
y_pred=ml.predict(X_test)
y_pred=pd.DataFrame(y_pred.reshape(-1,1))
y_pred.head(4)

--- 350.4873425960541 seconds needed to train ---


0
0  BENIGN
1  BENIGN
2  BENIGN
3  BENIGN

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# le= LabelEncoder()
# y_test=le.fit_transform(y_test)
# y_test

In [ ]:
# let us check accuracy
# import metrics library
from sklearn import metrics
print("accuracy is: ", metrics.accuracy_score(y_test,y_pred))
# import confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print("f1 score: ", f1_score(y_test,y_pred,average='weighted'))
print("precision score: ", precision_score(y_test, y_pred, average='weighted'))
print("recall score: ", recall_score(y_test, y_pred, average='weighted'))

accuracy is:  0.9975874587899254
[[240451     21      8      4     62     35      0      8      0      0
     101      0      0      0      0]
 [   101     94      0      0      0      0      0      0      0      0
       0      0      0      0      0]
 [    19      0  13487      0      2      0      0      0      0      0
       0      0      0      0      0]
 [     5      0      0   1076      4      0      0      0      0      0
       0      0      0      0      0]
 [   217      0      0      4  24288      0      0      0      0      0
       2      0      0      0      0]
 [     7      0      0      0      0    580      1      0      0      0
       0      0      1      0      0]
 [     0      0      0      0      0      2    637      0      0      0
       0      0      0      0      0]
 [     1      0      0      0      0      0      0    813      0      0
       0      0      0      0      0]
 [     0      0      0      0      0      0      0      0      2      0
       0      0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


precision score:  0.9974965703000676
recall score:  0.9975874587899254


##### Ada boost algorithm

In [ ]:
# let us create and run different models on the dataset
# let us use randomforest
# import libraries
from sklearn.ensemble import AdaBoostClassifier
clf=AdaBoostClassifier(random_state=96)
import time
stime = time.time()
clf.fit(x_train,y_train)
print("--- %s seconds needed to train ---" % (time.time() - stime))
print("training score: ",clf.score(x_train, y_train))
y_pred=clf.predict(x_test)
y_pred=pd.DataFrame(y_pred.reshape(-1,1))
y_pred.head(4)

--- 175.72682547569275 seconds needed to train ---
training score:  0.8571103738237565


0
0  0
1  0
2  0
3  0

In [ ]:
# let us check accuracy
# import metrics library
from sklearn import metrics
print("accuracy is: ", metrics.accuracy_score(y_test,y_pred))
# import confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print("f1 score: ", f1_score(y_test,y_pred,average='weighted'))
print("precision score: ", precision_score(y_test, y_pred, average='weighted'))
print("recall score: ", recall_score(y_test, y_pred, average='weighted'))

accuracy is:  0.8562113967091893
[[240145      0      0      0    281      0      0      0      0      0
       0      0      0      0      0]
 [   215      0      0      0      0      0      0      0      0      0
       0      0      0      0      0]
 [  5008      0      0      0   8461      0      0      0      0      0
       0      0      0      0      0]
 [   370      0      0      0    778      0      0      0      0      0
       0      0      0      0      0]
 [  7962      0      0      0  16445      0      0      0      0      0
       0      0      0      0      0]
 [   548      0      0      0      0      0      0      0      0      0
       0      0      0      0      0]
 [   621      0      0      0      0      0      0      0      0      0
       0      0      0      0      0]
 [   878      0      0      0      0      0      0      0      0      0
       0      0      0      0      0]
 [     0      0      0      0      0      0      0      0      2      0
       0      0

#### stacking ensemble classifier

In [ ]:
X

Flow_Duration  Total_Fwd_Packets  ...  Idle_Max  Idle_Min
0        5.083333e-07           0.000000  ...   0.00000  0.000000
1        7.061107e-01           0.000032  ...   0.70500  0.705000
2        5.042358e-03           0.000000  ...   0.00000  0.000000
3        8.447685e-02           0.000032  ...   0.08333  0.083330
4        3.234167e-04           0.000000  ...   0.00000  0.000000
...               ...                ...  ...       ...       ...
999995   9.833333e-07           0.000005  ...   0.00000  0.000000
999996   5.914928e-01           0.000032  ...   0.52500  0.061882
999997   1.816667e-06           0.000005  ...   0.00000  0.000000
999998   4.610488e-02           0.000009  ...   0.00000  0.000000
999999   1.103333e-05           0.000009  ...   0.00000  0.000000

[998953 rows x 77 columns]

In [ ]:
y1

0
0       10
1        4
2        0
3        0
4        0
...     ..
998948   0
998949   2
998950   0
998951   0
998952  10

[998953 rows x 1 columns]

In [ ]:
# compare ensemble to each baseline classifier
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import StackingClassifier
from matplotlib import pyplot

In [ ]:
# get a stacking ensemble of models
def get_stacking():
	# define the base models
	level0 = list()
	level0.append(('lr', LogisticRegression()))
	level0.append(('knn', KNeighborsClassifier()))
	level0.append(('cart', DecisionTreeClassifier()))
	level0.append(('svm', SVC()))
	level0.append(('bayes', GaussianNB()))
	# define meta learner model
	level1 = LogisticRegression()
	# define the stacking ensemble
	model = StackingClassifier(estimators=level0, final_estimator=level1, cv=5)
	return model

In [ ]:
# get a list of models to evaluate
def get_models():
	models = dict()
	models['lr'] = LogisticRegression()
	models['knn'] = KNeighborsClassifier()
	models['cart'] = DecisionTreeClassifier()
	models['svm'] = SVC()
	models['bayes'] = GaussianNB()
	models['stacking'] = get_stacking()
	return models

In [ ]:
# define dataset
#X, y = data[:, :-1], data[:, -1]
X, y = X, y1
# get the models to evaluate
models = get_models()

In [ ]:

# get the dataset
# def get_dataset():
# 	X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=1)
# 	return X, y

# evaluate a give model using cross-validation
def evaluate_model(model, X, y):
	cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
	scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
	return scores

In [ ]:
# evaluate the models and store results
results, names = list(), list()
for name, model in models.items():
	scores = evaluate_model(model, X, y)
	results.append(scores)
	names.append(name)
	print('>%s %.3f (%.3f)' % (name, mean(scores), std(scores)))


>lr 0.926 (0.002)


KeyboardInterrupt: ignored

In [ ]:
# plot model performance for comparison
pyplot.boxplot(results, labels=names, showmeans=True)
pyplot.show()

#### voting ensemble classifier

In [ ]:
# compare hard voting to standalone classifiers
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
from matplotlib import pyplot

# get the dataset
def get_dataset():
	X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=2)
	return X, y

# get a voting ensemble of models
def get_voting():
	# define the base models
	models = list()
	models.append(('knn1', KNeighborsClassifier(n_neighbors=1)))
	models.append(('knn3', KNeighborsClassifier(n_neighbors=3)))
	models.append(('knn5', KNeighborsClassifier(n_neighbors=5)))
	models.append(('knn7', KNeighborsClassifier(n_neighbors=7)))
	models.append(('knn9', KNeighborsClassifier(n_neighbors=9)))
	# define the voting ensemble
	ensemble = VotingClassifier(estimators=models, voting='hard')
	return ensemble

# get a list of models to evaluate
def get_models():
	models = dict()
	models['knn1'] = KNeighborsClassifier(n_neighbors=1)
	models['knn3'] = KNeighborsClassifier(n_neighbors=3)
	models['knn5'] = KNeighborsClassifier(n_neighbors=5)
	models['knn7'] = KNeighborsClassifier(n_neighbors=7)
	models['knn9'] = KNeighborsClassifier(n_neighbors=9)
	models['hard_voting'] = get_voting()
	return models

# evaluate a give model using cross-validation
def evaluate_model(model, X, y):
	cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
	scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
	return scores

# define dataset
X, y = get_dataset()
# get the models to evaluate
models = get_models()
# evaluate the models and store results
results, names = list(), list()
for name, model in models.items():
	scores = evaluate_model(model, X, y)
	results.append(scores)
	names.append(name)
	print('>%s %.3f (%.3f)' % (name, mean(scores), std(scores)))
# plot model performance for comparison
pyplot.boxplot(results, labels=names, showmeans=True)
pyplot.show()